image:
  repository: docker.io/deislabs/secrets-store-csi
  tag: v0.0.6
  pullPolicy: Always

logLevel: 

## Install Default RBAC roles and bindings
rbac:
  install: true

## providers supported
providers:
  azure:
    enabled: false
    repository: mcr.microsoft.com/k8s/csi/secrets-store/provider-azure
    tag: 0.0.1
    imagePullPolicy: Always

  vault:
    enabled: false
    repository: hashicorp/secrets-store-csi-driver-provider-vault
    tag: 0.0.2
    imagePullPolicy: Always
