{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-driver-registrar
  namespace: {{ .Release.Namespace }}
{{ include "kv.labels" . | indent 2 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher
  namespace: {{ .Release.Namespace }}
{{ include "kv.labels" . | indent 2 }}
{{ end }}
