run:
  timeout: 5m
  # some of the linters don't work correctly with 1.18
  # xref: https://github.com/golangci/golangci-lint/issues/2649
  # we are not using generics, so we can pin this to 1.17
  go: '1.17'
  skip-dirs: []
  skip-files:
  - "zz_generated.*\\.go$"

linters:
  disable-all: true
  enable:
    - deadcode
    - durationcheck
    - exportloopref
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unused
    - varcheck
  # Run with --fast=false for more extensive checks (enables all linters)
  fast: true

issues:
  # default: 50
  max-issues-per-linter: 0

  # default: 3
  max-same-issues: 0

severity:
  # default: ''
  default-severity: error
