apiVersion: v1
entries:
  secrets-store-csi-driver:
  - apiVersion: v1
    appVersion: 0.0.12
    created: "2020-07-17T16:17:16.643387-07:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 7175b2b870d724e87b56d7dcacdd5da11442b73aca3648382f489bccff423522
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.15.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts/secrets-store-csi-driver-0.0.12.tgz
    version: 0.0.12
  - apiVersion: v1
    appVersion: 0.0.11
    created: "2020-07-17T16:17:16.641155-07:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 2751ae7aed8ea2fc7dcdcbbf26240fccb2eefd83d3943cef45bb58bb1d297692
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.15.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts/secrets-store-csi-driver-0.0.11.tgz
    version: 0.0.11
  - apiVersion: v1
    appVersion: 0.0.10
    created: "2020-07-17T16:17:16.639954-07:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 9fae95e4611c9c120ed12505e735680b70ed133ea987fd32db05046cb45eda9e
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.15.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts/secrets-store-csi-driver-0.0.10.tgz
    version: 0.0.10
  - apiVersion: v1
    appVersion: 0.0.9
    created: "2020-07-17T16:17:16.644187-07:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 0f74454ca36c979a352d8a7b6d847521897ebf78195527ed8946201a841887a7
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.15.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts/secrets-store-csi-driver-0.0.9.tgz
    version: 0.0.9
generated: "2020-07-17T16:17:16.638548-07:00"
